name:  movie_app


description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tmdb_api: ^2.2.0  # Updated version
  google_fonts: ^5.0.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0  # Added Riverpod dependency

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true